-- Migration: Audit Logging for ADOFOM E-Platform
-- Using schema provided by developer

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  actor_id uuid references auth.users(id),
  action_type text not null, -- 'INSERT', 'UPDATE', 'DELETE'
  table_name text not null,
  record_id uuid,
  old_data jsonb,
  new_data jsonb
);

-- Indexes for fast querying by admins
create index if not exists idx_audit_logs_actor on public.audit_logs(actor_id);
create index if not exists idx_audit_logs_table on public.audit_logs(table_name);
create index if not exists idx_audit_logs_created on public.audit_logs(created_at desc);
create index if not exists idx_audit_logs_record on public.audit_logs(record_id);

-- RLS: Only admins can SELECT; triggers (postgres role) can INSERT
alter table public.audit_logs enable row level security;

create policy "Admins can view audit logs"
  on public.audit_logs for select
  using (
    exists (
      select 1 from public.administrative_officers
      where id = auth.uid() and is_admin = true
    )
  );

-- Trigger function: auto-captures changes on critical tables
create or replace function public.log_audit_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_record_id uuid;
begin
  -- Safely extract id field as uuid
  begin
    if TG_OP = 'DELETE' then
      v_record_id := (OLD.id)::uuid;
    else
      v_record_id := (NEW.id)::uuid;
    end if;
  exception when others then
    v_record_id := null;
  end;

  insert into public.audit_logs (
    actor_id,
    action_type,
    table_name,
    record_id,
    old_data,
    new_data
  ) values (
    auth.uid(),
    TG_OP,
    TG_TABLE_NAME,
    v_record_id,
    case when TG_OP in ('UPDATE','DELETE') then to_jsonb(OLD) else null end,
    case when TG_OP in ('INSERT','UPDATE') then to_jsonb(NEW) else null end
  );

  if TG_OP = 'DELETE' then return OLD; else return NEW; end if;
end;
$$;

-- Attach trigger to critical tables
create or replace trigger audit_administrative_officers
  after insert or update or delete on public.administrative_officers
  for each row execute function public.log_audit_change();

create or replace trigger audit_adofom_news
  after insert or update or delete on public.adofom_news
  for each row execute function public.log_audit_change();

-- NOTE: Run this in your Supabase SQL editor.
-- The audit_logs table intentionally has no DELETE policy — logs are immutable.
-- To view logs: select * from audit_logs order by created_at desc limit 100;
